### ISSUE TITLE
Peer review buckchat use case diagram

### ISSUE THREAD

**Issue by abjay** [CS506/fall2016-group1#47]
Guys, please review the buckchat use case diagram. Here is the link to it: [Buckchat use case diagram](https://github.com/CS506/fall2016-group1/blob/master/docs/sprint3/design/buckchat-use-case-diagram.pdf)

**Comment by raghav4494** [comment]
Hi Abhi. I have gone through that. It looks nice. I'm not sure the way, the arrows are used to link intro page to home page are fine or not. If they are right, then the diagram is okay for me.

**Comment by zach27** [comment]
Good start, Abhi. I have a few suggestions, but if what you found in the book or online contradicts these, ignore my suggestions since I don't know a lot about use-case diagrams.

1. Just have one instance of each use-case. `Login` is repeated.
1. I think the diagram should be higher level so that all use-cases are at the same level, roughly (no use-case pointing to another use-case, unless you use an `includes` or `uses` relationship like I am seeing online). The way the diagram is currently means the user can only login and register. No reason to group use-cases according to the page??
1.  I don't think the `Logout` use-cases should be linked back to the user. The use-case diagram should just show *abilities*, not order of events.
1. Make the text consistently verbs? E.g. Instead of `Bucket list`, have `View bucket list`? (Since the diagram shows *abilities*)

What do you guys think? Don't spend much time on revisions, though. This can be done after our presentation.
